# Disable sudo to speed up the build
sudo: false

language: python

python:
 - "3.7"

env:
  - CODECOV_TOKEN="9a7b0691-eff9-49e2-89d8-15c51a8df636"

cache: pip

before_install:
  - "pip install -r requirements-testing.txt"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/tracklater"

install: pip install -e .

before_script:
  - "flake8 ."
  - "mypy tracklater"

script: pytest --cov=. --cov-report term

after_success:
  - codecov
