language: python

python:
 - "3.7"

before_install:
  - "pip install -r requirements-testing.txt"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/tracklater"

install: pip install -e .

script: pytest --cov=. --cov-report term

after_success:
  - codecov