version: "3"

services:
  tracklater:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - "~/.ssh:/root/.ssh-mount"
      - "./:/code"
      - "~/.config/tracklater.json:/root/.config/tracklater.json"
      - "~/Documents:/home/eerovilpponen/Documents"
